name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: uv run pytest test_dataclassgen.py

  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6

      - name: Run linters
        run: |
          uv run ruff check --output-format=github || exit_status=1
          uv run ruff format --check || exit_status=1

          exit "${exit_status:-0}"

  typecheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5

      - uses: astral-sh/setup-uv@v6

      - name: Set up Python environment
        run: |
          uv sync
          echo "$PWD/.venv/bin" >> "$GITHUB_PATH"

      - uses: jakebailey/pyright-action@v2
